# Generated by Django 3.2.7 on 2021-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm', '0002_gnmuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='bias',
            field=models.FloatField(default=0, verbose_name='bias'),
        ),
    ]
