# Generated by Django 3.2.7 on 2021-09-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnm', '0003_deposit_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellinterval',
            name='azimut',
            field=models.FloatField(default=0.0, verbose_name='azimut'),
        ),
        migrations.AddField(
            model_name='wellinterval',
            name='content',
            field=models.ForeignKey(default='3a743c25-77de-48e9-a704-8e588f9e377a', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gnm.rock', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellinterval',
            name='depth_from',
            field=models.FloatField(default=0.0, verbose_name='depth_from'),
        ),
        migrations.AddField(
            model_name='wellinterval',
            name='depth_to',
            field=models.FloatField(default=0.0, verbose_name='depth_to'),
        ),
        migrations.AddField(
            model_name='wellinterval',
            name='zenit',
            field=models.FloatField(default=0.0, verbose_name='zenit'),
        ),
    ]
