"""deposit_offset

Revision ID: 0342fa05a31a
Revises: 03ced94de4be
Create Date: 2021-05-04 16:38:47.079736

"""
from alembic import op
import sqlalchemy as sa
import neuroAPI.database.ext


# revision identifiers, used by Alembic.
revision = '0342fa05a31a'
down_revision = '03ced94de4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('offset', sa.Numeric(), nullable=False, comment='Deposit offset',
                                        server_default='0'))
    op.alter_column('deposits', 'offset', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits', 'offset')
    # ### end Alembic commands ###
