"""indices_rock

Revision ID: 03ced94de4be
Revises: b6b9e63ed87b
Create Date: 2021-04-26 18:29:41.850935

"""
from alembic import op
import sqlalchemy as sa
import neuroAPI.database.ext


# revision identifiers, used by Alembic.
revision = '03ced94de4be'
down_revision = 'b6b9e63ed87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rocks', ['deposit_id', 'name'])
    op.create_unique_constraint(None, 'rocks', ['deposit_id', 'index'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rocks', type_='unique')
    op.drop_constraint(None, 'rocks', type_='unique')
    # ### end Alembic commands ###
