"""well_interval_parameters

Revision ID: b1f12a7c245b
Revises: 8a10c4507e62
Create Date: 2021-05-16 23:10:46.069504

"""
from alembic import op
import sqlalchemy as sa
import neuroAPI.database.ext


# revision identifiers, used by Alembic.
revision = 'b1f12a7c245b'
down_revision = '8a10c4507e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well_intervals', sa.Column('azimut', sa.Numeric(), nullable=True, comment='Interval azimut'))
    op.add_column('well_intervals', sa.Column('depth_from', sa.Numeric(), nullable=True, comment='Interval depth from'))
    op.add_column('well_intervals', sa.Column('depth_to', sa.Numeric(), nullable=True, comment='Interval depth to'))
    op.add_column('well_intervals', sa.Column('zenit', sa.Numeric(), nullable=True, comment='Interval zenit'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well_intervals', 'zenit')
    op.drop_column('well_intervals', 'depth_to')
    op.drop_column('well_intervals', 'depth_from')
    op.drop_column('well_intervals', 'azimut')
    # ### end Alembic commands ###
