"""neuralmodel_dump

Revision ID: b6b9e63ed87b
Revises: e484698c0414
Create Date: 2021-04-26 15:30:07.778738

"""
from alembic import op
import sqlalchemy as sa
import neuroAPI.database.ext
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6b9e63ed87b'
down_revision = 'e484698c0414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neural_models', sa.Column('dump', sa.LargeBinary(), nullable=False, comment='NM dump'))
    op.drop_column('neural_models', 'weights')
    op.drop_column('neural_models', 'structure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neural_models', sa.Column('structure', postgresql.BYTEA(), autoincrement=False, nullable=False,
                                             comment='NM structure'))
    op.add_column('neural_models', sa.Column('weights', postgresql.BYTEA(), autoincrement=False, nullable=False,
                                             comment='NM weights'))
    op.drop_column('neural_models', 'dump')
    # ### end Alembic commands ###
