"""fix

Revision ID: e484698c0414
Revises: 6262f227c7aa
Create Date: 2021-04-21 23:14:55.152886

"""
from alembic import op
import sqlalchemy as sa
import neuroAPI.database.ext


# revision identifiers, used by Alembic.
revision = 'e484698c0414'
down_revision = '6262f227c7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('name', sa.String(length=64), nullable=False, comment='Deposit name'))
    op.drop_column('deposits', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False,
                                        comment='Deposit name'))
    op.drop_column('deposits', 'name')
    # ### end Alembic commands ###
